[tool.poetry]
name = "aws-cdk-ci"
version = "1.0.0"
description = ""
authors = []
license = ""

[tool.poetry.dependencies]
python = "^3.13"
boto3 = "1.35.87"
aws-sam-cli = "1.132.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
