[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
boto3 = "1.35.91"
ansible = "11.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
